POST http://localhost:8080/api/questions/3
Content-Type: application/json

{
  "QuestionID": 5,
  "QuestionText": "",
  "MockID": "Attempt01",
  "DomainID": "Data Catalog",
  "CorrectAnswer": "Use a Resource Policy and Assume IAM role in job, Use lakeformation",
  "QuestionsOptions": "Use a Resource Policy and Assume IAM role in job,Use lakeformation,Use sts:AssumeRole inside an ETL Job, Use s3a to configure custom credentials"
}

###
GET http://127.0.0.1:8081/api/questions

